spring.application.name=bff-sucursal

server.port= 8082

spring.mvc.cors.enabled=true

# Clave secreta para JWT
jwt.secret=NaviumSuperSecretKeyParaFirmaDeTokens2026!

spring.main.allow-bean-definition-overriding=true


